name: scheduler_dvm
description: Scheduler DVM for publishing signed Nostr events at a future time.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.12.1

dependencies:
  ndk: 0.8.4-dev.1
  path: ^1.9.1
  sembast: ^3.8.7

dev_dependencies:
  bip340: ">=0.3.0 <0.4.0"
  broadcast_queue_shim_for_ndk: ^0.2.1
  lints: ^6.0.0
  nostr_event_scheduler: ^0.1.1
  test: ^1.25.6
